version: 2
project_name: sage

git:
  tag_sort: semver

# Automatically determine the next version based on conventional commits
release:
  github:
    owner: crazywolf132
    name: sage
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Release {{ .Tag }} ({{ .Date }})
    
    Welcome to this new release!
  footer: |
    {{ if .Env.GORELEASER_PREVIOUS_TAG }}
    **Full Changelog**: https://github.com/crazywolf132/sage/compare/{{ .Env.GORELEASER_PREVIOUS_TAG }}...{{ .Tag }}
    {{ else }}
    **First Release**
    {{ end }}
  name_template: "{{.Version}}"

builds:
  - id: sage
    binary: sage
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags: 
      - "-s -w -X github.com/crazywolf132/sage/cmd.Version={{ .Version }}"
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: sage
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    files:
      - none*
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: false

changelog:
  sort: asc
  use: github
  abbrev: 0                # Full commit hashes in the changelog
  filters:
    exclude:
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
      - '^chore\\(deps\\):'
  groups:
    - title: 'Breaking Changes 🛠'
      regexp: "^.*!:+.*$"
      order: 0
    - title: 'New Features 🎉'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 1
    - title: 'Bug Fixes 🐞'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 2
    - title: 'Maintenance 🔧'
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 3
    - title: 'Documentation 📚'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 4
    - title: 'Other Changes'
      order: 999

before:
  hooks:
    - go mod tidy 