project_name: sage

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/crazywolf132/sage/internal/version.Version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  abbrev: 0                # Full commit hashes in the changelog
  from: "{{ .PreviousTag }}"  # Start changelog from previous tag
  to: "{{ .Tag }}"            # End changelog at current tag
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'Breaking Changes 🛠'
      regexp: "^.*!:+.*$"
      order: 0
    - title: 'New Features 🎉'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 1
    - title: 'Bug Fixes 🐞'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 2
    - title: 'Maintenance 🔧'
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 3
    - title: 'Documentation 📚'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 4
    - title: 'Other Changes'
      order: 999

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next" 